### ISSUE TITLE
Set up flask to use dotenv

### ISSUE THREAD

**Issue by jasoncarr0** [jsnxchrl/heartbox#1]
Set up flask to read environment variables from .env file on the server.

**Comment by jasoncarr0** [comment]
Is it correct/expected behaviour that the .env file is at the root of the virtualenv? That is where it seems python-dotenv loads it from by default.

Additionally, what are your thoughts on https://github.com/grauwoelfchen/flask-dotenv 
It seems like it's more integrated into the app, but also seems a bit heavyweight/fixed compared to python-dotenv. 
Swapping them out should be relatively easy and the setup is working fine with python-dotenv

**Comment by cheryllium** [comment]
No, the .env file should be located at the project root.

What are the advantages of switching to flask-dotenv? If python-dotenv works fine, then you know. "If it ain't broken don't fix it"

**Comment by cheryllium** [comment]
The library you are using to interface with the .env file should allow you to specify the path to the file.

**Comment by jasoncarr0** [comment]
The advantages might be better integration with flask. It can provide aliases and it initializes the app with the settings. I think python-dotenv should work fine (it may need to run before we initialize the app) since it sets the environment variables as in os, whereas flask-dotenv seems to have its own dictionary.

Corrected the .env location
